// Generated by pdfx init.
// See: https://pdfx.akashpise.dev/installation#theming
//
// Provides runtime theme overrides via React context.
// Wrap a subtree in <PdfxThemeProvider theme={myTheme}> to override defaults.

import { type DependencyList, type ReactNode, use } from "react"
import { type PdfxTheme, PdfxThemeContext } from "./pdfx-context"
import { theme as defaultTheme } from "./theme-file"

export interface PdfxThemeProviderProps {
  theme?: PdfxTheme
  children: ReactNode
}

export function PdfxThemeProvider({ theme, children }: PdfxThemeProviderProps) {
  const resolvedTheme = theme ?? defaultTheme
  return (
    <PdfxThemeContext.Provider value={resolvedTheme}>
      {children}
    </PdfxThemeContext.Provider>
  )
}

export function usePdfxTheme(): PdfxTheme {
  return use(PdfxThemeContext)
}

/**
 * Calls factory() and returns the result.
 * The deps parameter is accepted for API compatibility with existing callers.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function useSafeMemo<T>(factory: () => T, _deps: DependencyList): T {
  return factory()
}
